package com.mario.java.restful.api.hibernate.jpa.entity;

import java.util.List;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * Abstract class which represents the base domain for all domains used by the application.<br>
 * All domains must extend this class.
 *
 * @author marioluan
 *
 */
@MappedSuperclass
@ApiModel(subTypes = {UserEntity.class, PetEntity.class}, description = "base dto", parent = DatedEntity.class)
public abstract class BaseEntity extends DatedEntity {

	@Id
	@GeneratedValue
	@ApiModelProperty(value = "the identifier of the entity", readOnly = true, notes = "it is generated by the application")
	private Long id;

	@Transient
	private List<String> propertiesToBeDisplayed;

	/**
	 * @return the propertiesToBeDisplayed
	 */
	public List<String> getPropertiesToBeDisplayed() {
		return this.propertiesToBeDisplayed;
	}

	/**
	 * @param propertiesToBeDisplayed the propertiesToBeDisplayed to set
	 */
	public void setPropertiesToBeDisplayed(List<String> propertiesToBeDisplayed) {
		this.propertiesToBeDisplayed = propertiesToBeDisplayed;
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}
}
