package com.mario.java.restful.api.hibernate.jpa.entity;

import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * Abstract class which exposes a domain with dated attributes (createdAt, updatedAt).<br>
 *
 * All {@link BaseEntity} implementations should extend this class.
 * @author marioluan
 *
 */
@MappedSuperclass
@ApiModel(subTypes = {BaseEntity.class}, description = "dated dto")
public abstract class DatedEntity {

	private static final Logger LOGGER = Logger.getLogger(DatedEntity.class.getSimpleName());

	@Temporal(TemporalType.TIMESTAMP)
	@Column(insertable=true, updatable=false)
	@ApiModelProperty(value = "the date which the entity was created", readOnly = true, example = "2015-04-21T03:42:35.565+0000", notes = "it is generated by the application")
	private Date createdAt;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(insertable=false, updatable=true)
	@ApiModelProperty(value = "the date which the entity was updated", readOnly = true, example = "2016-03-21T03:41:35.565+0000", notes = "it is generated by the application")
	private Date updatedAt;

	/**
	 * @return the createdAt
	 */
	public Date getCreatedAt() {
		return this.createdAt;
	}

	/**
	 * @param createdAt the createdAt to set
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * @return the updatedAt
	 */
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	/**
	 * @param updatedAt the updatedAt to set
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@PrePersist
	private void prePersist(){
		LOGGER.info("prePersist()");

		this.createdAt = new Date();
	}

	@PreUpdate
	private void preUpdate(){
		LOGGER.info("preUpdate()");

		this.updatedAt = new Date();
	}
}
